#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
# Float small, non-resizable windows
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh
#$HOME/.config/yabai/cycle_win_focus_prev.sh
#$HOME/.config/yabai/cycle_win_focus_next.sh
#$HOME/.config/yabai/cycle_win_swap_prev.sh
#$HOME/.config/yabai/cycle_win_swap_next.sh

# global settings
yabai -m config                                 \
    external_bar                 all:30:0       \
    menubar_opacity              0.9            \
    mouse_follows_focus          on            \
    focus_follows_mouse          on            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.1           \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.1            \
    active_window_opacity        0.95            \
    normal_window_opacity        0.8           \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap
# 忽略的 app
yabai -m rule --add label=default_float app=".*" manage=off
# yabai -m rule --add app="^(Software Update|System Preferences|系统设置|Finder|访达|活动监视器|DeepL|Raycast|Proxifier|QQ|WeChat|微信|Telegram|Monica|Stats|CodeWhisperer|Fig|pot|LocalSend|MacZip|He3|SFM|sing-box)$" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add app="^Keka" manage=off


 yabai -m rule --add app="^(Google Chrome|Firefox|Microsoft Edge|Blisk|Arc)$" space=^1 
 yabai -m rule --add app="^(iTerm|iTerm2|Warp|Alacritty|alacritty)$" space=^2
 yabai -m rule --add app="^(QQ|WeChat|微信|Telegram|钉钉|腾讯会议)$" space=^3
 yabai -m rule --add app="^Spark$" space=^4
 yabai -m rule --add app ="^拼多多商家版$" space=^6
# yabai -m rule --add app="^(Discord|Twitter|Maipo)$" space=^5
# yabai -m rule --add app="^(音乐|网易云音乐|刺猬猫阅读|哔哩哔哩|Fluent Reader)$" space=^6

echo "yabai configuration loaded.."
