#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    external_bar                 all:25:0       \
    menubar_opacity              0.9            \
    mouse_follows_focus          on            \
    focus_follows_mouse          on            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.1           \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.1            \
    active_window_opacity        0.95            \
    normal_window_opacity        0.8           \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap
# 忽略的 app
yabai -m rule --add app="^(Software Update|System Preferences|System Settings|系统设置|活动监视器|DeepL|Raycast|Proxifier|Monica|Stats|pot|LocalSend|MacZip|He3|SFM|sing-box|rednote|小红书|预览|App Store)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Keka$" manage=off

echo "yabai configuration loaded.."
