theme = "catppuccin_macchiato"
# theme = "my"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
true-color = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint" #内联诊断

[editor.cursor-shape]
insert = "bar"
#normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace]
render = "all"

[keys.normal]
C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
# C-y = [
#   ':sh rm -f /tmp/unique-file',
#   ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
#   ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
#   ':open %sh{cat /tmp/unique-file}',
#   ':redraw',
# ]
