# scls
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"
feature_paths = true          # enable path completion
feature_citations = true

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[language-server.emmet-lsp]
command="emmet-language-server"
args = ["--stdio"]

[language-server.typos]
command = "typos-lsp"

[language-server.bacon]
command = "bacon-ls"

# append language server to existed languages
[[language]]
name = "rust"
language-servers = ["scls","rust-analyzer","bacon","typos"]
[language-server.rust-analyzer.config]
checkOnSave = { enable = false }
diagnostics = { enable = false }

[[language]]
name = "git-commit"
language-servers = [ "scls" ]

# introduce a new language to enable completion on any doc by forcing set language with :set-language stub
[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]

[[language]]
name = "json"
language-servers = ["scls","vscode-json-language-server" ]


[language-server.typescript-language-server.config]
plugins = [{ name = "@vue/typescript-plugin", location = "$HOME/node_modules/@vue/language-server", languages = ["vue"] }]

[language-server.volar]
command = "vue-language-server"
args = ["--stdio"]

[language-server.volar.config]
#vue = { hybridMode = false }
typescript = { tsdk = "$HOME/node_modules/typescript/lib" }

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "vue"
auto-format = true
language-servers = ["volar","typescript-language-server","tailwindcss-language-server","scls","typos"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server","superhtml","emmet-lsp","scls","typos"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server","scls","typos"]
